stages:
  - prepare
  - lint
  - test

composer_install:
  image: composer:2
  stage: prepare
  script:
    - composer install --no-ansi
  artifacts:
    untracked: true
    expire_in: 1 day

php_stan:
  image: composer:2
  stage: lint
  needs: ["composer_install"]
  script:
    - ./vendor/bin/phpstan analyse --no-progress Classes/ Tests/Unit
  artifacts:
    reports:
      codequality: gl-phpstan-report.json
    paths: [gl-phpstan-report.json]

php-cs-fixer:
  image: composer:2
  stage: lint
  needs: ["composer_install"]
  script:
    - ./vendor/bin/php-cs-fixer fix -v --dry-run --diff --using-cache false

phpunit:7.4:
  image: registry.b13.com/jroth/typo3_composerize:php74
  stage: test
  script:
    - ./vendor/bin/phpunit --coverage-text

phpunit:8.0:
  image: registry.b13.com/jroth/typo3_composerize:php80
  stage: test
  script:
    - ./vendor/bin/phpunit --coverage-text
