before_script:
  # Gitlab Package Versioning is not working with certain version string e.g. v0.0.1
  - export GITLAB_RELEASE_VERSION=$(echo "${CI_COMMIT_TAG}" | sed 's/[^0-9\.]//g')
  - export PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/composer-web-installer/${GITLAB_RELEASE_VERSION}"

stages:
  - prepare
  - lint
  - test
#  - build
#  - upload
#  - release

composer_install:
  image: composer:2
  stage: prepare
  script:
    - composer install --no-ansi
  artifacts:
    untracked: true
    expire_in: 1 day

php_stan:
  image: composer:2
  stage: lint
  needs: ["composer_install"]
  script:
    - ./vendor/bin/phpstan analyse --no-progress Classes/ Tests/Unit
  artifacts:
    reports:
      codequality: gl-phpstan-report.json
    paths: [gl-phpstan-report.json]

php-cs-fixer:
  image: composer:2
  stage: lint
  needs: ["composer_install"]
  script:
    - ./vendor/bin/php-cs-fixer fix -v --dry-run --diff --using-cache false

phpunit:7.4:
  image: php:7.4
  stage: test
  script:
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - ./vendor/bin/phpunit --coverage-text

phpunit:8.0:
  image: php:8.0
  stage: test
  script:
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - ./vendor/bin/phpunit --coverage-text
