stages:
  - prepare
  - lint
  - test
  - publish

variables:
  PHAR_ARTIFACT_NAME: "typo3-composerize"
  PHAR_FILE_NAME: "typo3-composerize.phar"

composer_install:
  image: composer:2
  stage: prepare
  script:
    - composer install --no-ansi
  artifacts:
    untracked: true
    expire_in: 1 day

php_stan:
  image: composer:2
  stage: lint
  needs: ["composer_install"]
  script:
    - ./vendor/bin/phpstan analyse --no-progress Classes/ Tests/Unit
  artifacts:
    reports:
      codequality: gl-phpstan-report.json
    paths: [gl-phpstan-report.json]

php-cs-fixer:
  image: composer:2
  stage: lint
  needs: ["composer_install"]
  script:
    - ./vendor/bin/php-cs-fixer fix -v --dry-run --diff --using-cache false

.phpunit: &phpunit
  image: registry.b13.com/jroth/typo3_composerize:php74
  stage: test
  artifacts:
    when: always
    paths:
      - phpunit-report.xml
    reports:
      junit: phpunit-report.xml
  script:
    - ./vendor/bin/phpunit --coverage-text --log-junit phpunit-report.xml

phpunit:7.4:
  image: registry.b13.com/jroth/typo3_composerize:php74
  <<: *phpunit

phpunit:8.0:
  image: registry.b13.com/jroth/typo3_composerize:php80
  <<: *phpunit

publish-package:
  image: curlimages/curl:latest
  stage: publish
  only:
    - tags
  variables:
    URL: "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
  script:
    - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
    - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
    - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
    - code=$(echo "$response" | tail -n 1)
    - body=$(echo "$response" | head -n 1)
    # Output state information
    - if [ $code -eq 201 ]; then
      echo "Package created - Code $code - $body";
      else
      echo "Could not create package - Code $code - $body";
      exit 1;
      fi

create-phar:
  image: composer:2
  stage: publish
  needs: ["composer_install", "php-cs-fixer", 'php_stan']
  script:
    - composer install --no-dev
    - composer global config minimum-stability dev
    - composer global require humbug/box
    - /tmp/vendor/bin/box compile
  artifacts:
    name: $PHAR_ARTIFACT_NAME
    paths:
      - ./build/$PHAR_FILE_NAME
    expire_in: 1 day

upload-phar:
  stage: publish
  image: curlimages/curl:latest
  needs: ["phar"]
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ./build/${PHAR_FILE_NAME} ${PACKAGE_REGISTRY_URL}/${PHAR_FILE_NAME}

publish-phar:
  stage: publish
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs: ["upload"]
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --description "Automated Release $CI_COMMIT_TAG" \
        --assets-link "{\"name\":\"${PHAR_FILE_NAME}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PHAR_FILE_NAME}\"}"
