#!/usr/bin/env php

<?php

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        /** @noinspection PhpIncludeInspection */
        require $file;
        break;
    }
}

use Symfony\Component\Console\Application;
use B13\Typo3Composerize\Command\CheckIntegrityCommand;
use B13\Typo3Composerize\Command\CreateComposerCommand;

$application = new Application();
$application->add(new CheckIntegrityCommand());
$application->add(new CreateComposerCommand());
$application->run();
