name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPStan
        run: vendor/bin/phpstan analyse --no-progress Classes/ Tests/Unit

      - name: PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix -v --dry-run --diff --using-cache false

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
    steps:
    - uses: actions/checkout@v2

    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        coverage: "none"
        extensions: "intl, zip"
        ini-values: "memory_limit=-1, phar.readonly=0"
        php-version: "${{ matrix.php-version }}"
        tools: composer

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: PHPUnit
      run: vendor/bin/phpunit --coverage-text --log-junit phpunit-report.xml
